export const ContentType = {
  'application/EDI-X12': 'application/EDI-X12',
  'application/EDIFACT': 'application/EDIFACT',
  'application/javascript': 'application/javascript',
  'application/octet-stream': 'application/octet-stream',
  'application/ogg': 'application/ogg',
  'application/pdf': 'application/pdf',
  'application/xhtml+xml': 'application/xhtml+xml',
  'application/x-shockwave-flash': 'application/x-shockwave-flash',
  'application/json': 'application/json',
  'application/ld+json': 'application/ld+json',
  'application/xml': 'application/xml',
  'application/zip': 'application/zip',
  'application/x-www-form-urlencoded': 'application/x-www-form-urlencoded',
  'audio/mpeg': 'audio/mpeg',
  'audio/x-ms-wma': 'audio/x-ms-wma',
  'audio/vnd.rn-realaudio': 'audio/vnd.rn-realaudio',
  'audio/x-wav': 'audio/x-wav',
  'image/gif': 'image/gif',
  'image/jpeg': 'image/jpeg',
  'image/png': 'image/png',
  'image/tiff': 'image/tiff',
  'image/vnd.microsoft.icon': 'image/vnd.microsoft.icon',
  'image/x-icon': 'image/x-icon',
  'image/vnd.djvu': 'image/vnd.djvu',
  'image/svg+xml': 'image/svg+xml',
  'multipart/mixed': 'multipart/mixed',
  'multipart/alternative': 'multipart/alternative',
  'multipart/related': 'multipart/related', // (using by MHTML (HTML mail).)
  'multipart/form-data': 'multipart/form-data',
  'text/css': 'text/css',
  'text/csv': 'text/csv',
  'text/html': 'text/html',
  'text/plain': 'text/plain',
  'text/xml': 'text/xml',
  'video/mpeg': 'video/mpeg',
  'video/mp4': 'video/mp4',
  'video/quicktime': 'video/quicktime',
  'video/x-ms-wmv': 'video/x-ms-wmv',
  'video/x-msvideo': 'video/x-msvideo',
  'video/x-flv': 'video/x-flv',
  'video/webm': 'video/webm',
  'application/vnd.oasis.opendocument.text': 'application/vnd.oasis.opendocument.text',
  'application/vnd.oasis.opendocument.spreadsheet':
    'application/vnd.oasis.opendocument.spreadsheet',
  'application/vnd.oasis.opendocument.presentation':
    'application/vnd.oasis.opendocument.presentation',
  'application/vnd.oasis.opendocument.graphics': 'application/vnd.oasis.opendocument.graphics',
  'application/vnd.ms-excel': 'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint': 'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation':
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/msword': 'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.mozilla.xul+xml': 'application/vnd.mozilla.xul+xml',
} as const;
